version: "3.7"

services:
  db:
    image: postgres
    container_name: go-api-db
    tty: true
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "25432:5432"
    volumes:
      - go-api:/var/lib/postgresql/data
volumes:
  go-api:
